### ISSUE TITLE
Default value with disabled on true 

### ISSUE THREAD

**Issue by michiel1995** [anomalylabs/relationship-field_type#9]
When you want do something like:
```
$fields['company'] = [

                    'disabled'=> true,
                    "type" => "anomaly.field_type.relationship",
                    "config" => [
                        "related" => CompanyModel::class,
                        "default_value" => $company,
                        "mode" => "dropdown",
                    ],

                ];
$builder->setFields($fields);
```

The disabled prevents it from processing all together since value could be snuck in.

**Comment by RyanThompson** [comment]
Still thinking on this one but can you reopen this in the main repository please? pyrocms/pyrocms and just prefix it like `[relationship-field_type]`

**Comment by michiel1995** [comment]
Yeah its easily to fix when using a hidden field in the view of the fieldtype.
